WITH STG_TRANSACTION_LINES AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID, TRANSACTION_LINE_ID, LOCATION_ID, DEPARTMENT_ID, ITEM_ID, AMOUNT, COST, UNITS ORDER BY TRANSACTION_ID) AS row_num
  FROM TRANSACTION_LINES
)
SELECT *
FROM STG_TRANSACTION_LINES
WHERE row_num = 1