WITH cte AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY ITEM_MERCHANDISE_DEPARTMENT_ID, DESCRIPTION, ITEM_MERCHANDISE_DEPARTMENT_NA ORDER BY ITEM_MERCHANDISE_DEPARTMENT_ID) AS row_num
  FROM ITEM_MERCHANDISE_DEPARTMENT
)
SELECT * FROM cte
WHERE row_num > 1
