WITH cte AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY ITEM_MERCHANDISE_SUBCLASS_ID, DESCRIPTION, ITEM_MERCHANDISE_SUBCLASS_NAME ORDER BY ITEM_MERCHANDISE_SUBCLASS_ID) AS row_num
  FROM ITEM_MERCHANDISE_SUBCLASS
)
SELECT *
FROM cte
WHERE row_num = 1