WITH cte AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY ITEM_MERCHANDISE_CLASS_ID, DESCRIPTION, ITEM_MERCHANDISE_CLASS_NAME ORDER BY ITEM_MERCHANDISE_CLASS_ID) AS row_num
  FROM ITEM_MERCHANDISE_CLASS
)
SELECT *
FROM cte
WHERE row_num = 1