WITH cte AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY DATE_LAST_MODIFIED, DEPARTMENT_ID, ISINACTIVE, NAME, WS_DESCRIPTION ORDER BY DEPARTMENT_ID) AS row_num
  FROM DEPARTMENTS
)
SELECT *
FROM cte
WHERE row_num = 1
