WITH cte AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY CLASS_ID, DATE_LAST_MODIFIED, FULL_NAME, ISINACTIVE, NAME ORDER BY CLASS_ID) AS row_num
  FROM {{ source('PUBLIC', 'CLASSES') }}
)
SELECT *
FROM cte
WHERE row_num = 1