WITH STG_TRANSACTIONS AS (
  SELECT *,
    ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID, TRANID, TRANSACTION_TYPE, TRANDATE, CHANNEL_ID ORDER BY TRANSACTION_ID) AS row_num
  FROM {{ source('PUBLIC', 'TRANSACTIONS') }}
)
SELECT * FROM STG_TRANSACTIONS
WHERE row_num > 1
