-- Define the SQL query for the view
SELECT
  i.ITEM_ID,
  i.SKU,
  i.TYPE_NAME,
  i.SALESDESCRIPTION,
  i.CLASS_ID,
  i.WS_MERCHANDISE_DEPARTMENT_ID,
  i.WS_MERCHANDISE_COLLECTION_ID,
  i.WS_MERCHANDISE_CLASS_ID,
  i.WS_MERCHANDISE_SUBCLASS_ID,
  imd.DESCRIPTION AS MERCHANDISE_DEPARTMENT_DESCRIPTION,
  imc.DESCRIPTION AS MERCHANDISE_CLASS_DESCRIPTION,
  ils.DESCRIPTION AS MERCHANDISE_SUBCLASS_DESCRIPTION
FROM STG_ITEMS i
LEFT JOIN STG_ITEM_MERCHANDISE_DEPARTMENT imd
  ON i.WS_MERCHANDISE_DEPARTMENT_ID = imd.ITEM_MERCHANDISE_DEPARTMENT_ID
LEFT JOIN STG_ITEM_MERCHANDISE_CLASS imc
  ON i.WS_MERCHANDISE_CLASS_ID = imc.ITEM_MERCHANDISE_CLASS_ID
LEFT JOIN STG_ITEM_MERCHANDISE_SUBCLASS ils
  ON i.WS_MERCHANDISE_SUBCLASS_ID = ils.ITEM_MERCHANDISE_SUBCLASS_ID;
