SELECT
  I.ITEM_ID,
  I.SKU,
  I.TYPE_NAME,
  I.SALESDESCRIPTION,
  C.CLASS_ID,
  C.DATE_LAST_MODIFIED AS CLASS_DATE_LAST_MODIFIED,
  C.FULL_NAME AS CLASS_FULL_NAME,
  C.ISINACTIVE AS CLASS_ISINACTIVE,
  C.NAME AS CLASS_NAME,
  MD.ITEM_MERCHANDISE_DEPARTMENT_ID,
  MD.DESCRIPTION AS DEPARTMENT_DESCRIPTION,
  MD.ITEM_MERCHANDISE_DEPARTMENT_NA,
  IC.ITEM_MERCHANDISE_COLLECTION_ID,
  IC.DESCRIPTION AS COLLECTION_DESCRIPTION,
  IC.ITEM_MERCHANDISE_COLLECTION_NA,
  MC.ITEM_MERCHANDISE_CLASS_ID,
  MC.DESCRIPTION AS CLASS_DESCRIPTION,
  MC.ITEM_MERCHANDISE_CLASS_NAME,
  SC.ITEM_MERCHANDISE_SUBCLASS_ID,
  SC.DESCRIPTION AS SUBCLASS_DESCRIPTION,
  SC.ITEM_MERCHANDISE_SUBCLASS_NAME,
  TLF.TRANSACTION_ID
FROM  {{ ref('STG_ITEMS') }} I
JOIN {{ ref('STG_CLASSES') }} C ON I.CLASS_ID = C.CLASS_ID
JOIN {{ ref('STG_ITEM_MERCHANDISE_DEPARTMENT') }} MD ON I.WS_MERCHANDISE_DEPARTMENT_ID = MD.ITEM_MERCHANDISE_DEPARTMENT_ID
JOIN {{ ref('STG_ITEM_MERCHANDISE_COLLECTION') }} IC ON I.WS_MERCHANDISE_COLLECTION_ID = IC.ITEM_MERCHANDISE_COLLECTION_ID
JOIN {{ ref('STG_ITEM_MERCHANDISE_CLASS') }} MC ON I.WS_MERCHANDISE_CLASS_ID = MC.ITEM_MERCHANDISE_CLASS_ID
JOIN {{ ref('STG_ITEM_MERCHANDISE_SUBCLASS') }} SC ON I.WS_MERCHANDISE_SUBCLASS_ID = SC.ITEM_MERCHANDISE_SUBCLASS_ID
JOIN {{ ref('TRANSACTIONS_LINES_FACT') }} TLF ON I.ITEM_ID = TLF.ITEM_ID
