-- Define the SQL query to join the tables
SELECT
  T.TRANSACTION_ID,
  T.TRANID,
  T.TRANSACTION_TYPE,
  T.TRANDATE,
  T.CHANNEL_ID,
  L.LOCATION_ID,
  L.ADDRESS,
  L.CITY,
  L.COUNTRY,
  D.DEPARTMENT_ID,
  D.NAME AS DEPARTMENT_NAME,
  I.ITEM_ID,
  I.SKU,
  I.TYPE_NAME,
  I.SALESDESCRIPTION,
  TL.AMOUNT,
  TL.COST,
  TL.UNITS
FROM {{ ref('STG_TRANSACTIONS') }} T
JOIN {{ ref('STG_TRANSACTIONS_LINES') }} TL ON T.TRANSACTION_ID = TL.TRANSACTION_ID
JOIN {{ ref('STG_CHANNEL') }} C ON T.CHANNEL_ID = C.LIST_ID
JOIN {{ ref('STG_LOCATIONS') }} L ON TL.LOCATION_ID = L.LOCATION_ID
JOIN {{ ref('STG_DEPARTMENTS') }} D ON TL.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN {{ ref('STG_ITEMS') }} I ON TL.ITEM_ID = I.ITEM_ID